"""empty message

Revision ID: 192aaad8e7d2
Revises: 1a125f25516b
Create Date: 2020-10-26 10:20:52.708055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192aaad8e7d2'
down_revision = '1a125f25516b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
