"""empty message

Revision ID: 61290759d4c0
Revises: 783cb755d290
Create Date: 2020-10-25 20:14:56.469095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61290759d4c0'
down_revision = '783cb755d290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
