"""empty message

Revision ID: 763dcedf2139
Revises: 2d8039f2b4d3
Create Date: 2020-10-26 14:22:00.815186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763dcedf2139'
down_revision = '2d8039f2b4d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
