"""empty message

Revision ID: 783ab7f6c6b3
Revises: 192aaad8e7d2
Create Date: 2020-10-26 10:21:11.965598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783ab7f6c6b3'
down_revision = '192aaad8e7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
